version: '3'

services:
  consul:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8500:8500"
    networks:
      - consul_network

networks:
  consul_network:
    driver: bridge
